### ISSUE TITLE
Docker on RasPi not working

### ISSUE THREAD

**Issue by tabannis** [Webreaper/SolisAgileManager#124]
I know this is already known about, but the side-issue where this was previously discussed has been closed.

The docker container for Raspberry Pi releases isn't working. For me it generates the following error in docker on run...

`exec /app/SolisManager: no such file or directory`

My system

Raspberry Pi 5 running LibreElec, Docker 27.5.1, using the following docker compose config:

```
solismanager:
        container_name: solismanager
        image: webreaper/solisagilemanager:latest
        ports:
            - '5168:5168'
        restart: unless-stopped
        volumes:
            - /storage/system/solismanagerdocker:/appdata
```

**Comment by Webreaper** [comment]
Yep, I need to fix this, but unsure how at present!

Is your Pi an Arm64?

**Comment by tabannis** [comment]
Yup, it is indeed Arm64

**Comment by Webreaper** [comment]
Thanks. Yeah, may be a bad base image.

**Comment by dqj999** [comment]
This isn't the cause of the problem, but I thought that it was port 5169 that was used rather than 5168. That's certainly what my working RasPi system is using. 

There do seem to be other solar management systems that work with Docker on RasPis but I've don't have enough knowledge to figure out what needs to be done.

**Comment by tabannis** [comment]
I changed the port number to 5168 in the yaml so it wouldn't conflict with my (Working) raspi installation on 5169 👍

**Comment by Webreaper** [comment]
You need to change the port on one side, not the other. The port internal to the container is always 5169; if you want to expose an alternative port from the container then the port setting should be:

`5168:5169`

**Comment by tabannis** [comment]
Ah, that's good to know. Thanks, I'll update my configuration,👍

**Comment by baruba-cons** [comment]
Shouldn't `platforms: ${{ matrix.platform }}` be `platforms: ${{ matrix.docker-platforms }}`?

https://github.com/Webreaper/SolisAgileManager/blob/0986ebf9e3dcbe5e24b1100ded2c7fba5cd36471/.github/workflows/ci.yml#L92-L95

**Comment by Webreaper** [comment]
Nice spot - could very well be. Testing.... 

@tabannis - could you try pulling the `dev` tag once this build has completed, and let me know if this works?

https://github.com/Webreaper/SolisAgileManager/actions/runs/13647818389

**Comment by Webreaper** [comment]
Can you remove the platform line and see if it works?

**Comment by tabannis** [comment]
Same result 👎

**Comment by baruba-cons** [comment]
Found ["exec format error" running arm64 docker image using dotnet](https://stackoverflow.com/questions/78623677) on SO which might be useful.

@martincostello You've [blogged](https://blog.martincostello.com/look-ma-no-hands-publishing-containers-with-the-dotnet-sdk/) about a new way to publish an app to a container image, do you know if [multi-platform manifest](https://github.com/dotnet/sdk-container-builds/issues/87) is possible using this method?

**Comment by martincostello** [comment]
Hey @baruba-cons - sorry, I've not tried to do that myself, so I don't know.

Maybe @baronfel can help you out.

**Comment by Webreaper** [comment]
I'm already using `docker/build-push-action` to create the multi-platform manifest. I think the issue might be that the arm64/Pi base image doesn't have `sh` so might need another shell. I wonder if `bash` would work instead?

**Comment by Webreaper** [comment]
That new build process looks good, but I'm not sure it's that much different to what I'm already doing. Are there any github actions that leverage it yet?

**Comment by Webreaper** [comment]
Actually I see Martin mentions how to use this in a github action, so I could give this a try.

However, I'm *already* publishing multi-arch manifest images to Docker and they all work just fine - except the Arm64 one (which doesn't work on RaspPi). I'd rather understand what's wrong - without having to buy a raspberry pi. 😁

**Comment by baruba-cons** [comment]
Since publish uses `--self-contained true`, do you need [.NET Runtime Dependencies](https://hub.docker.com/r/microsoft/dotnet-runtime-deps/)?

See [No such file or directory while running a docker container](https://stackoverflow.com/questions/78969598/no-such-file-or-directory-while-running-a-docker-container) for more details.

**Comment by baruba-cons** [comment]
I've pushed a image to docker hub using dotnet publish and it was pretty straightforward.  If you want to try it from your dev machine try the following (ref: [Containerize a .NET app reference](https://learn.microsoft.com/en-us/dotnet/core/containers/publish-configuration)).  Ensure you login with `docker login registry.hub.docker.com` from CLI.

```shell
dotnet publish SolisManager/SolisManager.csproj -t:PublishContainer 
  -p:RuntimeIdentifiers=\"osx-x64;osx-arm64;linux-x64;linux-arm64;linux-arm\" 
  -p:ContainerFamily="alpine" -p:ContainerRegistry="registry.hub.docker.com" 
  -p:ContainerRepository="webreaper/solisagilemanager" -p:ContainerImageTag="dev"
```

**Comment by Webreaper** [comment]
Thanks, I'll give that a go. Does the image work on RaspPi?

**Comment by baruba-cons** [comment]
I tried it on my project and it worked with an older RPI 3.  Maybe tabannis would be willing to test if you push the dev image tag.

**Comment by Webreaper** [comment]
Cool, will try it.

**Comment by tabannis** [comment]
I'm certainly willing to give it a go 👍

**Comment by Webreaper** [comment]
Okay, tried it, but I'm getting a failure here, and no idea why. 😕  Any ideas @baruba-cons ? At first I thought it might be because it's not building on a Mac host, but even removing the osx targets gives a failure restoring the linux packages.

```
Run dotnet publish SolisManager/SolisManager.csproj -p:RuntimeIdentifiers=osx-x64;osx-arm64;linux-x64;linux-arm64;linux-arm \ -p:Version=1.0.493-dev --self-contained true -p:PublishTrimmed=false \ -t:PublishContainer -p:ContainerFamily=alpine -p:ContainerRegistry=registry.hub.docker.com \ -p:ContainerRepository=***/solisagilemanager -p:ContainerImageTag=alpha
  
  Determining projects to restore...
/home/runner/work/SolisAgileManager/SolisAgileManager/SolisManager.Client/SolisManager.Client.csproj : error NU1102: Unable to find package Microsoft.NETCore.App.Runtime.Mono.osx-x[6](https://github.com/Webreaper/SolisAgileManager/actions/runs/13716190706/job/38361436801#step:7:6)4 with version (= 9.0.2) [/home/runner/work/SolisAgileManager/SolisAgileManager/SolisManager/SolisManager.csproj]
/home/runner/work/SolisAgileManager/SolisAgileManager/SolisManager.Client/SolisManager.Client.csproj : error NU1102:   - Found 129 version(s) in nuget.org [ Nearest version: 9.0.0-preview.7.24405.7 ] [/home/runner/work/SolisAgileManager/SolisAgileManager/SolisManager/SolisManager.csproj]
/home/runner/work/SolisAgileManager/SolisAgileManager/SolisManager.Client/SolisManager.Client.csproj : error NU1102:   - Found 0 version(s) in /usr/share/dotnet/library-packs [/home/runner/work/SolisAgileManager/SolisAgileManager/SolisManager/SolisManager.csproj]
  Restored /home/runner/work/SolisAgileManager/SolisAgileManager/SolisManager/SolisManager.csproj (in 2.98 sec).
  Failed to restore /home/runner/work/SolisAgileManager/SolisAgileManager/SolisManager.Client/SolisManager.Client.csproj (in 2.98 sec).
  Restored /home/runner/work/SolisAgileManager/SolisAgileManager/SolisManager.Inverters.SolarEdge/SolisManager.Inverters.SolarEdge.csproj (in 2.97 sec).
  Restored /home/runner/work/SolisAgileManager/SolisAgileManager/SolisManager.Shared/SolisManager.Shared.csproj (in 2.97 sec).
  Restored /home/runner/work/SolisAgileManager/SolisAgileManager/SolisManager.Inverters.Solis/SolisManager.Inverters.Solis.csproj (in 1[6](https://github.com/Webreaper/SolisAgileManager/actions/runs/13716190706/job/38361436801#step:7:7) ms).
Error: Process completed with exit code 1.
```

https://github.com/Webreaper/SolisAgileManager/actions/runs/13716245277/job/38361598602

**Comment by Webreaper** [comment]
Okay, last problem is auth for the push. Currently I get: 

```
JSDCE minifyWhitespace --exportES6 -o /tmp/emscripten_temp_plh31536/dotnet.native.jso1.js
  SolisManager -> /home/runner/work/SolisAgileManager/SolisAgileManager/SolisManager/bin/Release/net9.0/linux-x64/publish/
  Building image '***/solisagilemanager' with tags 'alpha' on top of base image 'mcr.microsoft.com/dotnet/runtime-deps:9.0'.
  Uploading layer 'sha256:7cf63256a31a4cc44f6defe8e1af95363aee5fa75f30a248d95cae684f87c53c' to 'registry.hub.docker.com'.
  Uploading layer 'sha256:3c23d8dbc423f8078d17e36b95bf61e71c982800d38a361e4afb6c658bc590cb' to 'registry.hub.docker.com'.
  Uploading layer 'sha256:9a3805478f07d9a3736b8429fe850131ee3a6324bf91e3fc0a8490472c7519a4' to 'registry.hub.docker.com'.
  Uploading layer 'sha256:27aaca73a128a[34](https://github.com/Webreaper/SolisAgileManager/actions/runs/13717890116/job/38366551311#step:7:35)129101a656e4aa2bf2baedec0739e822eeef5c0063d541b9f' to 'registry.hub.docker.com'.
Error: /usr/share/dotnet/sdk/9.0.200/Containers/build/Microsoft.NET.Build.Containers.targets(252,5): error CONTAINER1013: Failed to push to the output registry: CONTAINER1008: Failed retrieving credentials for "registry.hub.docker.com": No matching auth specified for registry 'registry.hub.docker.com' in Docker config. [/home/runner/work/SolisAgileManager/SolisAgileManager/SolisManager/SolisManager.csproj]
Error: Process completed with exit code 1.
```

Don't know what additional stuff I need to do in a github action to authenticate with DockerHub (given I already execute the `login-action` github workflow beforehand). Will have to keep digging.

**Comment by baronfel** [comment]
@Webreaper can you check if logging in results in any change to the Docker config file? The .NET SDK reads the Docker config file and parses authentication information from it for each registry you try to push to, and it could be that the content in that file isn't valid for whatever reason? In the abstract this _should_ work, and I have a [sample actions workflow](https://github.com/baronfel/sdk-container-demo/actions/runs/12244073237/job/34155014702) that shows it working, but there of course may be environmental differences or configuration differences in play.

**Comment by baruba-cons** [comment]
From [authenticating to container registries](https://aka.ms/dotnet/containers/auth) maybe try setting environment variables  `DOTNET_CONTAINER_REGISTRY_UNAME` & `DOTNET_CONTAINER_REGISTRY_PWORD`?

**Comment by baronfel** [comment]
`docker config inspect` doesn't really deal with the docker config/auth file - the file lives at `$HOME/.docker/config.json` by default, but it's possible to configure the system to look in different locations. IIRC the spec is `DOCKER_CONFIG/config.json` for maximal flexibility.

You could also try switching actions to the azure login one (which doesn't use the docker CLI at all), and specifying the registry. I'd love to make this work natively though.

**Comment by baronfel** [comment]
> From [authenticating to container registries](https://aka.ms/dotnet/containers/auth) maybe try setting environment variables `DOTNET_CONTAINER_REGISTRY_UNAME` & `DOTNET_CONTAINER_REGISTRY_PWORD`?

please don't rely on those environment variables - they are visible in MSBuild logs and are only supported because VS container publish needs a way to provide credentials to MSBuild.

**Comment by Webreaper** [comment]
@baronfel Had a bit of a hectic day at work, so not had any time to look at this. 

Could you point me in the direction of how I'd update the action/workflow to log out changes to the config file? Happy to add what you recommend and then see what the output looks like.

**Comment by baruba-cons** [comment]
Not sure if this would make a difference, but reading the documentation `docker.io` can be used instead after .NET SDK 8.0.100.

https://github.com/Webreaper/SolisAgileManager/blob/44a78cfdc283b667d778563209896a654281e5e6/SolisManager/SolisManager.csproj#L14

**Comment by Webreaper** [comment]
OMG, setting the registry to docker.io worked!

https://github.com/Webreaper/SolisAgileManager/actions/runs/13735542801

Could somebody with a Pi try pulling webreaper/solisagilemanager:alpha and tell me if it works?

**Comment by tabannis** [comment]
Still not running, but the logs now have this error:

`exec /app/SolisManager: exec format error`

**Comment by tabannis** [comment]
When I specify docker compose with the platform... it ssys this

`image with reference webreaper/solisagilemanager:alpha was found but its platform (linux/amd64) does not match the specified platform (linux/arm64)`

Is alpha build available in arm64 flavour?

**Comment by Webreaper** [comment]
It should be - I specified linux-arm64 on in the `ContainerRuntimeIdentifiers` section. 

@baronfel - any ideas? Seems we have the same issue as I had before using the docker-build-push action....

**Comment by tabannis** [comment]
Maybe try adding `linux/arm/v8` in `ContainerRuntimeIdentifiers`?

**Comment by Webreaper** [comment]
No such runtime Identifier: https://learn.microsoft.com/en-us/dotnet/core/rid-catalog#known-rids

Perhaps 'linux-musl-arm64' - trying...

**Comment by Webreaper** [comment]
That's built. Give it a try.

If that doesn't work it'll have to wait until Monday!

**Comment by tabannis** [comment]
Nope :(  oh well. Have a nice weekend (y)

**Comment by Webreaper** [comment]
Dammit. Ah well, the garden is calling.

**Comment by baruba-cons** [comment]
I'm pretty sure if you change `ContainerRuntimeIdentifiers` to `RuntimeIdentifiers` it'll work, I'm not clear what the former does.

https://github.com/Webreaper/SolisAgileManager/blob/b53fefcd5c9fa1f86f8b98f024454f53ca8b665d/SolisManager/SolisManager.csproj#L13

**Comment by baronfel** [comment]
It's a bit complex. `RuntimeIdentifiers` is kind of load-bearing in that `Restore` understands `RuntimeIdentifiers` and will use it to determine if any cross-platform implementation packages should be downloaded at `Restore`-time. So my guidance there is 

> If you a) are making a platform-specific application, and b) know what platforms you would like to target, then always specify all of your supported platforms in `RuntimeIdentifiers` in your applications' project

Secondly, the multi-arch container support works like a logical `foreach` over your `RuntimeIdentifiers`:

```
foreach rid in rids do:
  publish rid-specific container
publish multi-arch container wrapper with each rid-specific container inside of it
```

What this means is that if you specify a RID in `RuntimeIdentifiers` that _isn't valid for the container base image you've chosen_ (for example, any non-Linux RID) then container publish will fail. It's for this reason that we provide `ContainerRuntimeIdentifiers` - it lets you define a subset of `RuntimeIdentifiers` to publish for _when publishing a container only_.

Hope that clears things up a bit.

The workflow that @Webreaper [linked above](https://github.com/Webreaper/SolisAgileManager/actions/runs/13735542801/job/38418751572#step:6:35) is showing a single-RID image only, which _might_ be caused by the use of `--self-contained true`. If I recall, that flag requires that the app be built for a single RID, and so in the absence of a RID on the command line or in the csproj it'll use the RID of the executing platform. My concrete suggestions for @Webreaper:

* remove `--self-contained true` and `-p:PublishTrimmed=false` from your `dotnet publish` command and put this in your csproj instead:

```xml
<PropertyGroup>
  <PublishTrimmed>false</PublishTrimmed>
  <PublishSelfContained>true</PublishSelfContained>
</PropertyGroup>
```

* rename your current `ContainerRuntimeIdentifiers` property to just `RuntimeIdentifiers` and create a new `ContainerRuntimeIdentifiers` property with just `linux-arm64;linux-arm;linux-x64`.
  * This should result in a properly multi-arch image

One thing I also notice - you have both a 'normal' Linux and 'musl' Linux RIDs - we currently do not support pushing a single multi-arch image with mixed libc implementations like this. Typically, most apps would have this as two separate images: one for 'glibc'-based Linux (linux-arm64, linux-arm, linux-x64) and one for 'musl'-based Linux (linux-musl-arm64, linux-musl-x64). You can do this with our tooling if you do two separate publish calls:
  * one with `ContainerRuntimeIdentifiers` set to `linux-arm64;linux-arm;linux-x64`
  * one with `ContainerRuntimeIdentifiers` set to `linux-musl-arm64;linux-musl-x64`

When you do this, you should provide a different tag for the musl-based image. Most people will call this `-alpine` or similar. People split apps into these two tags because the base operating systems can have drastically different behaviors and usually picking musl-based Linux is an explicit choice.

**Comment by Webreaper** [comment]
Thanks. I only added the musl ones because I was grasping at straws. I'll remove them.

Can I leave the OSX targets so they'll work for Docker on Darwin?

**Comment by baronfel** [comment]
No - on Mac, Docker runs Linux containers. This is also generally the case on Windows, but technically Windows containers are A Thing (just not a thing that is widely used outside of specific back-compat use cases).

**Comment by Webreaper** [comment]
Oh, yes, good point. Thanks.

And yeah, Windows is weird, and Windows Docker is even more weird. 🤣

**Comment by Webreaper** [comment]
Okay, trying those here: https://github.com/Webreaper/SolisAgileManager/actions/runs/13746674281 ...

**Comment by Webreaper** [comment]
The problem with 
```
<PropertyGroup>
  <PublishTrimmed>false</PublishTrimmed>
  <PublishSelfContained>true</PublishSelfContained>
</PropertyGroup>
```
is that I also build non-dockerised builds, which **must** be self-contained. Will the command-line override the csproj in this case?

**Comment by Webreaper** [comment]
Okay, that seems fine. 

But the multi-arch still doesn't seem to be working even with those changes - the alpha tag still only has `linux-amd64`.

**Comment by tabannis** [comment]
Can confirm this, no change when pulling on my pi5.

**Comment by baruba-cons** [comment]
Have you tried it without `--self-contained true`?  Maybe remove those from csproj and yml and try again.  At this point it's a process of elimination and then it can be fine tuned.

https://github.com/Webreaper/SolisAgileManager/blob/a914ea0b67c4cbccb39f2042569bf355f06c87ec/SolisManager/SolisManager.csproj#L9

https://github.com/Webreaper/SolisAgileManager/blob/a914ea0b67c4cbccb39f2042569bf355f06c87ec/.github/workflows/ci.yml#L163

**Comment by baronfel** [comment]
If you create a binlog of your publish (add `-bl`) then that can be investigated to find out example what is going on. As I said above, I believe `--self-contained true` on your command line is forcing you into single-RID mode (this is true for all `publish` actions).

**Comment by Webreaper** [comment]
I don't have 'self-contained true' on my command line any more, so it can't be that.

**Comment by Webreaper** [comment]
Okay, I removed it from the wrong job. Will fix later.

**Comment by Webreaper** [comment]
Removed from the dotnet container build job. Still not generating multi-arch for the `alpha` tag.

**Comment by baronfel** [comment]
This is _fascinating_. The `PublishSelfContained` flag is forcing the SDK to provide a RID, and that automatically-provided RID is what's blocking the SDK's natural multi-RID container publishing.

If you set `<PublishSelfContained Condition="'$(RuntimeIdentifier)' != ''">true</PublishSelfContained>`, this allows the SDK-driven multi-RID container publish to continue, but at least on my machine I then hit a race condition in the WebAssembly build targets the RID-specific builds then trigger:

```
> dotnet publish -t:PublishContainer -bl
Restore complete (0.4s)
  SolisManager.Shared succeeded (0.2s) → E:\Code\Scratch\SolisAgileManager\SolisManager.Shared\bin\Release\net9.0\SolisManager.Shared.dll
  SolisManager.Inverters.SolarEdge succeeded (0.2s) → E:\Code\Scratch\SolisAgileManager\SolisManager.Inverters.SolarEdge\bin\Release\net9.0\SolisManager.Inverters.SolarEdge.dll
  SolisManager.Inverters.Solis succeeded (0.3s) → E:\Code\Scratch\SolisAgileManager\SolisManager.Inverters.Solis\bin\Release\net9.0\SolisManager.Inverters.Solis.dll
  SolisManager.Client succeeded (4.2s) → E:\Code\Scratch\SolisAgileManager\SolisManager.Client\bin\Release\net9.0\wwwroot
  SolisManager.Shared succeeded (0.2s) → E:\Code\Scratch\SolisAgileManager\SolisManager.Shared\bin\Release\net9.0\SolisManager.Shared.dll
  SolisManager.Shared succeeded (0.1s) → E:\Code\Scratch\SolisAgileManager\SolisManager.Shared\bin\Release\net9.0\SolisManager.Shared.dll
  SolisManager.Inverters.SolarEdge succeeded (0.1s) → E:\Code\Scratch\SolisAgileManager\SolisManager.Inverters.SolarEdge\bin\Release\net9.0\SolisManager.Inverters.SolarEdge.dll
  SolisManager.Inverters.Solis succeeded (0.1s) → E:\Code\Scratch\SolisAgileManager\SolisManager.Inverters.Solis\bin\Release\net9.0\SolisManager.Inverters.Solis.dll
  SolisManager.Inverters.Solis succeeded (0.1s) → E:\Code\Scratch\SolisAgileManager\SolisManager.Inverters.Solis\bin\Release\net9.0\SolisManager.Inverters.Solis.dll
  SolisManager.Inverters.SolarEdge succeeded (0.2s) → E:\Code\Scratch\SolisAgileManager\SolisManager.Inverters.SolarEdge\bin\Release\net9.0\SolisManager.Inverters.SolarEdge.dll
  SolisManager.Shared succeeded (0.2s) → E:\Code\Scratch\SolisAgileManager\SolisManager.Shared\bin\Release\net9.0\SolisManager.Shared.dll
  SolisManager.Client failed with 1 error(s) (2.2s)
    E:\code\nuget-packages\microsoft.net.sdk.webassembly.pack\9.0.2\build\Microsoft.NET.Sdk.WebAssembly.Browser.targets(367,5): error MSB4018:
      The "GenerateWasmBootJson" task failed unexpectedly.
      System.IO.IOException: The process cannot access the file 'E:\Code\Scratch\SolisAgileManager\SolisManager.Client\obj\Release\net9.0\blazor.boot.json' because it is being used by ano
      ther process.
         at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
         at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 un
      ixCreateMode)
         at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCr
      eateMode)
         at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullabl
      e`1 unixCreateMode)
         at System.IO.File.Create(String path)
         at Microsoft.NET.Sdk.WebAssembly.GenerateWasmBootJson.Execute()
         at Microsoft.Build.BackEnd.TaskExecutionHost.Execute()
         at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(TaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, T
      askExecutionMode howToExecuteTask)
  SolisManager.Client succeeded (4.5s) → E:\Code\Scratch\SolisAgileManager\SolisManager.Client\bin\Release\net9.0\wwwroot
  SolisManager.Client succeeded (4.5s) → E:\Code\Scratch\SolisAgileManager\SolisManager.Client\bin\Release\net9.0\wwwroot
  SolisManager.Inverters.Solis succeeded (0.1s) → E:\Code\Scratch\SolisAgileManager\SolisManager.Inverters.Solis\bin\Release\net9.0\SolisManager.Inverters.Solis.dll
  SolisManager.Inverters.SolarEdge succeeded (0.2s) → E:\Code\Scratch\SolisAgileManager\SolisManager.Inverters.SolarEdge\bin\Release\net9.0\SolisManager.Inverters.SolarEdge.dll
  SolisManager succeeded (12.5s) → bin\Release\net9.0\linux-arm64\publish\
  SolisManager succeeded with 1 warning(s) (32.6s) → bin\Release\net9.0\linux-arm\publish\
    E:\Code\Scratch\SolisAgileManager\SolisManager\Services\InverterManager.cs(28,12): warning CS8618: Non-nullable field 'inverterAPI' must contain a non-null value when exiting constructor. Consider adding the 'required' modifier or declaring the field as nullable.
  SolisManager failed (3.0s) → bin\Release\net9.0\publish\

Build failed with 1 error(s) and 1 warning(s) in 55.1s
```

**Comment by Webreaper** [comment]
Okay, merged the PR, but the build failed: https://github.com/Webreaper/SolisAgileManager/actions/runs/13758662323/job/38470180724

```
  Optimizing assemblies for size may change the behavior of the app. Be sure to test after publishing. See: https://aka.ms/dotnet-illink
/usr/share/dotnet/sdk/9.0.200/Sdks/Microsoft.NET.Sdk.StaticWebAssets/targets/Microsoft.NET.Sdk.StaticWebAssets.Compression.targets(366,5): error : The process cannot access the file '/home/runner/work/SolisAgileManager/SolisAgileManager/SolisManager.Client/obj/Release/net9.0/blazor.publish.boot.json' because it is being used by another process. [/home/runner/work/SolisAgileManager/SolisAgileManager/SolisManager.Client/SolisManager.Client.csproj]
```

Also seems to have tagged the image wrong: `Uploading tag 'alpha-linux-arm64' to 'docker.io'.`

Doesn't feel like we're getting any closer. 😄 Any ideas?

**Comment by Webreaper** [comment]
Okay, maybe a red herring. Just run a couple of pipelines for unrelated fixes, and it's built. So some race condition (I think you mentioned earlier @baronfel).

The `alpha` tag is now showing as multi-arch - so @tabannis do you want to give it a go?

<img width="834" alt="Image" src="https://github.com/user-attachments/assets/748bd20a-4f53-435c-8ff8-b85aec3838c3" />

**Comment by tabannis** [comment]
That's sounding promising. However... I've just tried an image pull and container recreation remotely, but something had gone wrong and I've lost my vpn (Wireguard) home. Doh. 

I'll have to check when I get home after work to see what's happened. Bear with me caller.

**Comment by Webreaper** [comment]
LOL. Anyone else hate technology? 😄

**Comment by baronfel** [comment]
Confirmed that the multi-arch manifest looks good, however the generated containers have the wrong Entrypoint:

```
"Entrypoint": [
                "dotnet",
                "/app/SolisManager.dll"
            ]
```

the container base image used (runtime-deps) doesn't include `dotnet` itself, because it's used as the base for self-contained applications. I _suspect_ that the shenanigans we had to do to prevent the win-x64 RID from being used in the outer build has impacted the way we compute which entrypoint to use. Will take a look.

**Comment by baronfel** [comment]
Ok, with https://github.com/Webreaper/SolisAgileManager/pull/137 I've fixed this for good - I've got the app running locally in a container, no problem.

**Comment by Webreaper** [comment]
Okay, merged and built: https://github.com/Webreaper/SolisAgileManager/actions/runs/13767665226

@tabannis - over to you to pull/test.

@baronfel - what's the next steps here? Are there going to be improvements to `dotnet publish -t:PublishContainer` in a future version of msbuild, to make this more intuitive and less painful? Feels like if there'd been errors failing the build and indicating the conflicts between `self-contained true` and `PublishContainer` this might have been easier to debug? 

Also, will you be putting together improved docs for people who might want to use this in future? Perhaps a full and comprehensive answer here might be useful too: https://stackoverflow.com/questions/79370927/how-to-build-an-asp-net-core-9-blazor-app-and-dockerise-it-for-a-32-bit-raspberr

**Comment by Webreaper** [comment]
I see you've answered some of that here: https://github.com/Webreaper/SolisAgileManager/pull/137#issuecomment-2710890615

**Comment by baronfel** [comment]
For posterity:

You're pushing some design boundaries with this project for sure :) We've never had a real use case/example of someone doing self-contained, multi-arch, blazorwasm apps. I've logged a [couple issues](https://github.com/dotnet/sdk-container-builds/issues?q=state%3Aopen%20label%3A%22Area%3A%20Multi-RID%20Publishing%22) for us to work through on the container publish side so some of these workarounds are no longer needed, but your project has also illustrated some fundamental problems in the browserwasm MSBuild logic that are causing the race conditions and re-builds/re-work that you've seen. So now I get to go show another team how they can do better/get better perf/do less work and everybody gets to benefit.

Additional commentary:

I think it would be entirely reasonable for this project to say "this was a fun experiment, but due to bugs and/or our confidence level in being able to influence the image generation without pinging @baronfel we'd rather wait", if you wanted to. I've got some work to do across a few teams to make the experience better, get docs/guides written, etc. But _to me_ I think in a month or two half of the changes I made can be removed, and the other half are actually useful - ContainerAppUser documents a precondition about your container that's explicitly different from the suggested security behaviors for containers, for example. Totally up to you, and I don't want to force anyone to use tech they're not comfortable with and (importantly) don't understand fully.

**Comment by Webreaper** [comment]
Thanks. If this gets us a working RaspPi container, I'll stick with it - because it's a step up from the docker 'build-push-action' that I was using before. If @tabannis tries it and we still get an `exec format` error, then I might comment it all out for now. We'll see. 

Regarding the Damselfly project, I'll leave it - I don't have much time for active dev of that one, and it's taken long enough to get the multi-arch build working as it is.... but maybe later this year when you've improved the tooling and docs a bit more I might have a play. Thanks for the help though, and glad to have pushed the tooling forwards. 

One thing that might help a lot is to add a `dotnet new` template which is 'dockerised hosted blazor app' which puts all this in place for people (perhaps with an option for config folder etc). That could also help act as a canonical example that people could reference when they start playing with this stuff.

**Comment by tabannis** [comment]
![Image](https://github.com/user-attachments/assets/21bd6b9e-1feb-47b2-996d-f4e89644d644)
Success! (As for what crashed wireguard, anyone's guess!)

**Comment by tabannis** [comment]
Ok, partial success..

```
Created config folder: /app/SolisManager.

Creating log folder /app/SolisManager

Unable to initialise logs: System.IO.IOException: The file '/app/SolisManager' already exists.

   at System.IO.FileSystem.CreateDirectory(String fullPath, UnixFileMode unixCreateMode)

   at System.IO.Directory.CreateDirectory(String path)

   at SolisManager.Program.InitLogConfiguration(LoggerConfiguration config, String logFolder) in /home/runner/work/SolisAgileManager/SolisAgileManager/SolisManager/Program.cs:line 293
```

I'm not able to complete the config scrreen - `Error: Unknown error saving config`

**Comment by Webreaper** [comment]
I think I know what that is - the startup arg is wrong. And easy to fix. I'll have a look later.

**Comment by Webreaper** [comment]
Did you map the config folder to /appdata/config?

**Comment by tabannis** [comment]
Nope, used the sample compose config from README modifying the appdata volume as needed.
```
solismanager:
        container_name: solismanager
        image: webreaper/solisagilemanager:alpha
        ports:
            - '5168:5169'
        restart: unless-stopped
        volumes:
            - /storage/system/solismanagerdocker:/appdata
        platform: linux/arm64
```

**Comment by Webreaper** [comment]
Cool, that should be correct. 

I've moved 
```
      <ContainerAppCommandArgs>/appdata</ContainerAppCommandArgs>
```
from an `<ItemGroup>` to a `<PropertyGroup>` - @baronfel should that make any difference? It seems startup arg isn't working right.

**Comment by tabannis** [comment]
The appdata mapping seems to be working as I can create a folder (using the container console) in /appdata and it creates it on my persistent storage.

**Comment by baronfel** [comment]
It matters a lot actually - properties and items are fundamentally different things in MSBuild. https://learn.microsoft.com/en-us/dotnet/core/containers/publish-configuration#containerappcommandargs

Items are lists and are able to easily be aggregated, iterated over, etc. we use them to safely accrue args to apply to the container. If you check the generated containers with 'docker inspect' you should see that the args are applied (I did when I was building this locally earlier today). If you use a property instead you'll not see that argument applied.

**Comment by Webreaper** [comment]
Yeah, it's the startup arg that isn't being passed to the app. It should pass `/appdata` as the command line arg, which tells it to use that folder. It's possible the change above in the latest build might have fixed that, but if not Chet will have to opine.

But we're close. At least it starts!

Worst case, I could change the app to default to that folder or to pick up the startup folder from an env var as a workaround...

**Comment by tabannis** [comment]
Nothing at all in the "Config" folder that the container has created at `/app/config`

For info this is the entrypoint shown: `/app/SolisManager /app/SolisManager /appdata /appdata`

**Comment by baronfel** [comment]
Alright, _this_ is a real blocker. It's another side effect of https://github.com/dotnet/sdk-container-builds/issues/623. The outer build is (incorrectly) setting the value on the inner build, _but the inner build is also re-setting those same values if they are present_.  There are a few other side effects here, but I don't see a way to work around them at this time.

**Comment by tabannis** [comment]
Ok. If I specify entrypoint in the compose yaml as  `/app/SolisManager /appdata` it runs, and creates a .log file in` /appdata`...

```
[18:59:43.137--INF] ===========================================================
[18:59:43.209--INF] Application started. Build version v1.0.515.0 Logs being written to /appdata
[18:59:44.050--INF] Now listening on: http://[::]:5169
[18:59:44.059--INF] Application started. Press Ctrl+C to shut down.
[18:59:44.059--INF] Hosting environment: Production
[18:59:44.060--INF] Content root path: /app
[19:01:19.468--INF] Saving config to server...
[19:01:19.485--ERR] Uncaught Exception occurred: Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at SolisManager.Services.InverterManager.SaveConfig(SolisManagerConfig newConfig) in /home/runner/work/SolisAgileManager/SolisAgileManager/SolisManager/Services/InverterManager.cs:line 1073
   at SolisManager.APIWrappers.EndpointMapper.<>c.<<MapSaveConfigAPI>b__5_0>d.MoveNext() in /home/runner/work/SolisAgileManager/SolisAgileManager/SolisManager/APIWrappers/EndpointMapper.cs:line 168
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Http.RequestDelegateFactory.ExecuteTaskResult[T](Task`1 task, HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddlewareImpl.<Invoke>g__Awaited|10_0(ExceptionHandlerMiddlewareImpl middleware, HttpContext context, Task task)
[19:02:00.056--ERR] Unexpected exception during inverter state refresh
System.NullReferenceException: Object reference not set to an instance of an object.
   at SolisManager.Services.InverterManager.UpdateInverterState() in /home/runner/work/SolisAgileManager/SolisAgileManager/SolisManager/Services/InverterManager.cs:line 866
```

**Comment by tabannis** [comment]
And for info, If I put the `SolisManagerConfig.json` from my "live" instance of the app into the /appdata it generates the same error.

At least it's running and putting data in the right place now :)

**Comment by Webreaper** [comment]
> Alright, _this_ is a real blocker. ..... So long story short, wait for [dotnet/sdk-container-builds#623](https://github.com/dotnet/sdk-container-builds/issues/623) to get released before continuing with this effort

I have a few people champing at the bit for the Raspberry Pi docker image, so I think I can work around this for now: I can have the app look for an Env Var if no command-line is provided, and the docker-compose for RPi would have to be like:
```
solismanager:
        container_name: solismanager
        image: webreaper/solisagilemanager:alpha
        ports:
            - '5168:5169'
        restart: unless-stopped
        env: 
            - SOLISMANAGER_CONFIGFOLDER=/appdata
        volumes:
            - /storage/system/solismanagerdocker:/appdata
        platform: linux/arm64
```
And just remove the `ContainerAppCommandArgs` tag from the csproj. Once the sdk-container-builds is fixed, then we can have the command-line param automatic (but then still keep the env var for backward compatibility. 

@baronfel - how is the container-builds thing released? Part of .Net's SDK? So would we have to wait for .Net 10 to get these improvements, or will there be incremental updates (e.g., 9.0.3 etc)?

**Comment by Webreaper** [comment]
@tabannis - the above change is building. Feel free to give it a go. 

https://github.com/Webreaper/SolisAgileManager/actions/runs/13774184822

(please check my docker-compose syntax...)

**Comment by baronfel** [comment]
It's part of the SDK _and_ a NuGet package, but I won't know which vehicles we would ship a fix in until we make a fix and figure out where we are in the release cycle at that point.

**Comment by Webreaper** [comment]
Thanks. Makes sense.

**Comment by tabannis** [comment]
Ok, had to make a change to your compose syntax:

```
 solismanager:
    container_name: solismanager
    image: webreaper/solisagilemanager:alpha
    ports:
    - '5168:5169'
    restart: unless-stopped
    environment:
    - SOLISMANAGER_CONFIGFOLDER=/appdata  # Corrected format
    volumes:
    - /storage/system/solismanagerdocker:/appdata
    platform: linux/arm64
```
But... Bingo!
![Image](https://github.com/user-attachments/assets/50e23ef7-78ac-4ee5-b52c-801db28b29f4)

**Comment by Webreaper** [comment]
Awesome. Thanks for all your help and input everyone! @tabannis for all the testing, and @baronfel for all the input and wisdom.

**Comment by baronfel** [comment]
https://github.com/dotnet/sdk/pull/47424 Here's the proposed PR for the SDK. This is currently targeting .NET 10 preview 4 (May) but after discussion and merge we'll try to get it backported to 9.0.300 as well for folks that don't want to live on the bleeding edge.

**Comment by Webreaper** [comment]
Okay, I think I have a solution to the `ContainerAppCommandArgs` bug that'll sort us out for now. As @baronfel would expect, it involves Scott H - he wrote [this useful article](https://www.hanselman.com/blog/detecting-that-a-net-core-app-is-running-in-a-docker-container-and-skippablefacts-in-xunit) and the 'is running in docker' thing still holds true today. 

So I've now code code which basically says:
```
if( SOLISMANAGER_CONFIGFOLDER env var is set )
{
    // Use that
}
else if( IsRunningInDocker )
{
   // Default to /appdata
}
else
{
   // Use the command-line parameter passed in to determine the config folder
}
```

This means that we don't need the `SOLISMANAGER_CONFIGFOLDER` env var and people's existing docker-compose will work as expected without any changes. So I think I can merge this now. @tabannis - could you pull the latest `alpha` tag, remove the config folder env var, and confirm this works for you? (I tested this morning so I'm confident it will).

@baronfel one thing I did notice was that this morning I had to re-run the build because the push to docker.io failed - I think that race condition is still there. Not the end of the world, but useful to fix if you can. It worked when I re-ran the job.

**Comment by tabannis** [comment]
Looking good..

```
[07:39:40.478--INF] Application is shutting down...
[07:39:40.701--INF] Coravel's Scheduling service is now stopped.
[07:39:52.161--INF] ===========================================================
[07:39:52.225--INF] Application started. Build version v1.0.518.0 Logs being written to /appdata
[07:39:52.227--INF] Running in Docker
[07:39:52.527--INF] Loaded cached Solcast data from /appdata/Solcast-cache.json
[07:39:53.064--INF] Now listening on: http://[::]:5169
[07:39:53.073--INF] Application started. Press Ctrl+C to shut down.
[07:39:53.073--INF] Hosting environment: Production
[07:39:53.078--INF] Content root path: /app 
```

I've not got any history table/graph or a history CSV, but I assume that's because I'm running this alpha build in simulation mode?

**Comment by Webreaper** [comment]
It should pick up the existing history, but the main thing is that's working. 

I'll look to do a full release later today. We did it!

**Comment by Webreaper** [comment]
FYI - I've just been testing the multi-tag stuff for when I do a release; as part of that I've now deleted the `alpha` tag. So we're back to just `dev` and a full release on `latest`.

**Comment by Webreaper** [comment]
Got a release out... took 3 attempts to run the pipeline before it succeeded, due to this race condition (mentioned earlier):

```
/home/runner/.nuget/packages/microsoft.net.sdk.webassembly.pack/9.0.2/build/Microsoft.NET.Sdk.WebAssembly.Browser.targets(658,5): error MSB4018: The "GenerateWasmBootJson" task failed unexpectedly. [/home/runner/work/SolisAgileManager/SolisAgileManager/SolisManager.Client/SolisManager.Client.csproj]
/home/runner/.nuget/packages/microsoft.net.sdk.webassembly.pack/9.0.2/build/Microsoft.NET.Sdk.WebAssembly.Browser.targets(658,5): error MSB4018: System.IO.IOException: The process cannot access the file '/home/runner/work/SolisAgileManager/SolisAgileManager/SolisManager.Client/obj/Release/net9.0/blazor.publish.boot.json' because it is being used by another process. [/home/runner/work/SolisAgileManager/SolisAgileManager/SolisManager.Client/SolisManager.Client.csproj]
```

**Comment by tabannis** [comment]
It could be my imagination but I think I'm seeing a good app performance
boost since switching to docker 😀

**Comment by Webreaper** [comment]
Docker itself certainly won't make the app faster, and even upgrading to .Net 10 is unlikely to have much of an effect with this particular app (rendering might be a fraction faster if there's been more JIT Blazor improvements, but I suspect not enough to notice.
 
So I think that's placebo effect. 😁

**Comment by baronfel** [comment]
> Thanks, done. Are you working to make it so that file isn't locked (i.e., copied/cached) in future, so that we can have parallel builds with everything working one day?

I've started that conversation, but I don't control the timeline so I can't make any promises unfortunately :(

**Comment by Webreaper** [comment]
No problem at all. I know you've got a lot going on, and having slightly slower builds that succeed first time is fine (currently I have to do ~3 runs each time before it succeeds).
